import { Platform, StatusBar } from 'react-native';
import { ScaledSheet, moderateScale } from 'react-native-size-matters';
import { Colors, Spacing } from '@/app/shared/constants/Theme';

export const styles = ScaledSheet.create({
  container: {
    flex: 1,
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    backgroundColor: Colors.white,
  },
  mainHeader: {
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.sm,
    backgroundColor: Colors.white,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: moderateScale(16),
  },
  mainHeaderTitle: {
    fontSize: moderateScale(24),
    fontWeight: '800',
    color: '#1A1A1A',
  },
  mainHeaderSubtitle: {
    fontSize: moderateScale(13),
    color: '#0059B2',
    fontWeight: '600',
    marginTop: moderateScale(2),
  },
  headerRightIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(16),
  },
  iconBtn: {
    padding: moderateScale(4),
  },
  actionButton: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: moderateScale(12),
    paddingHorizontal: moderateScale(16),
    height: moderateScale(48),
    borderWidth: 1,
    borderColor: Colors.border,
    marginTop: Spacing.sm,
  },
  searchInput: {
    flex: 1,
    marginLeft: moderateScale(8),
    fontSize: moderateScale(14),
    color: Colors.text,
  },
  closeSearchBtn: {
    padding: moderateScale(4),
  },
  filtersWrapper: {
    paddingVertical: Spacing.sm,
  },
  filtersScrollContent: {
    paddingHorizontal: Spacing.md,
    gap: moderateScale(10),
  },
  filterPill: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(10),
    borderRadius: moderateScale(20),
  },
  filterPillActive: {
    backgroundColor: '#0059B2',
  },
  filterText: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: '#4B5563',
  },
  filterTextActive: {
    color: Colors.white,
  },
  filterPillAdd: {
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(10),
    borderRadius: moderateScale(20),
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterTextAdd: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: '#6B7280',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: Spacing.xl,
  },
  filterModalContent: {
    borderRadius: moderateScale(16),
    padding: Spacing.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  filterModalTitle: {
    marginBottom: Spacing.md,
  },
  filterInput: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: moderateScale(10),
    paddingHorizontal: moderateScale(12),
    minHeight: moderateScale(44),
    fontSize: moderateScale(15),
    color: '#1F2937',
    marginBottom: Spacing.lg,
  },
  filterModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: Spacing.sm,
  },
  filterModalBtn: {
    paddingVertical: moderateScale(10),
    paddingHorizontal: moderateScale(16),
    borderRadius: moderateScale(8),
  },
  filterModalBtnPrimary: {
    backgroundColor: '#0059B2',
  },
  filterModalBtnText: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: '#6B7280',
  },
  filterModalBtnTextPrimary: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: Colors.white,
  },
  listContent: {
    paddingHorizontal: Spacing.md,
  },
  chatRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: moderateScale(16),
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  avatarWrapper: {
    position: 'relative',
    marginRight: moderateScale(14),
  },
  avatarImage: {
    width: moderateScale(45),
    height: moderateScale(45),
    borderRadius: moderateScale(28),
  },
  avatarIconBox: {
    width: moderateScale(45),
    height: moderateScale(45),
    borderRadius: moderateScale(100),
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusDot: {
    position: 'absolute',
    bottom: 3,
    right: 0,
    width: moderateScale(14),
    height: moderateScale(14),
    borderRadius: moderateScale(7),
    borderWidth: 2,
    borderColor: Colors.white,
  },
  chatContent: {
    flex: 1,
  },
  chatHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: moderateScale(4),
  },
  chatName: {
    fontSize: moderateScale(16),
    fontWeight: '700',
    color: '#1A1A1A',
    flex: 1,
    paddingRight: moderateScale(10),
  },
  chatNameUnread: {
    color: '#1A1A1A',
  },
  chatTime: {
    fontSize: moderateScale(12),
    color: '#9CA3AF',
    fontWeight: '500',
  },
  chatTimeUnread: {
    color: '#0059B2',
    fontWeight: '600',
  },
  chatSubHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: moderateScale(8),
    paddingRight: moderateScale(4),
  },
  chatMessage: {
    fontSize: moderateScale(14),
    color: '#6B7280',
    flex: 1,
  },
  chatMessageUnread: {
    color: '#0059B2',
    fontWeight: '600',
    fontStyle: 'italic',
  },
  unreadDot: {
    width: moderateScale(8),
    height: moderateScale(8),
    borderRadius: moderateScale(4),
    backgroundColor: '#0059B2',
    marginLeft: moderateScale(8),
  },
  unreadBadge: {
    minWidth: moderateScale(20),
    height: moderateScale(20),
    borderRadius: moderateScale(10),
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: moderateScale(8),
    paddingHorizontal: moderateScale(6),
  },
  unreadBadgeText: {
    color: '#FFFFFF',
    fontSize: moderateScale(10),
    fontWeight: 'bold',
  },
  tagRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  tagPill: {
    paddingHorizontal: moderateScale(10),
    paddingVertical: moderateScale(4),
    borderRadius: moderateScale(12),
  },
  tagText: {
    fontSize: moderateScale(10),
    fontWeight: '700',
  },
  extraIconsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  smallAvatar: {
    width: moderateScale(20),
    height: moderateScale(20),
    borderRadius: moderateScale(10),
    borderWidth: 1.5,
    borderColor: Colors.white,
  },
  membersOnlineText: {
    fontSize: moderateScale(11),
    color: '#9CA3AF',
    marginLeft: moderateScale(10),
    fontWeight: '500',
  },
  fab: {
    position: 'absolute',
    right: Spacing.md,
    bottom: moderateScale(100), // Adjusted to float above tab bar
    width: moderateScale(56),
    height: moderateScale(56),
    borderRadius: moderateScale(18),
    backgroundColor: '#0059B2',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#0059B2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
});
